apiVersion: v1
kind: Service
metadata:
  name: &app-name svc-go-payment-authorizer
  namespace: test-a
  labels:
    app: *app-name
spec:
  type: ClusterIP
  ports:
  - port: 65000
    targetPort: 65000
    protocol: TCP
    name: http
  selector:
    app: go-payment-authorizer
